import { AuthVerificationParams } from '../../../shared/types';

export enum NAVIGATION_KEYS {
	// Public screens
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	AUTH_VERIFICATION = 'AUTH_VERIFICATION',
	REGISTER_SUCCESS = 'REGISTER_SUCCESS',
	FORGOT_PASSWORD = 'FORGOT_PASSWORD',
	RESET_PASSWORD_VERIFICATION = 'RESET_PASSWORD_VERIFICATION',
	SET_NEW_PWD = 'SET_NEW_PWD',
	SET_NEW_PWD_SUCCESS = 'SET_NEW_PWD_SUCCESS',

	// Stacks
	BOTTOM_TABS = 'BOTTOM_TABS',
	HOME_STACK = 'HOME_STACK',
	SETTINGS_STACK = 'SETTINGS_STACK',

	// Private screens
	HOME = 'HOME',
	SETTINGS = 'SETTINGS',
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.REGISTER]: undefined;
	[NAVIGATION_KEYS.AUTH_VERIFICATION]: AuthVerificationParams;
	[NAVIGATION_KEYS.REGISTER_SUCCESS]: undefined;
	[NAVIGATION_KEYS.FORGOT_PASSWORD]: undefined;
	[NAVIGATION_KEYS.RESET_PASSWORD_VERIFICATION]: AuthVerificationParams;
	[NAVIGATION_KEYS.SET_NEW_PWD]: AuthVerificationParams;
	[NAVIGATION_KEYS.SET_NEW_PWD_SUCCESS]: undefined;
	[NAVIGATION_KEYS.BOTTOM_TABS]: undefined;
	[NAVIGATION_KEYS.HOME]: undefined;
	[NAVIGATION_KEYS.SETTINGS]: undefined;
};
