export enum NAVIGATION_KEYS {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	AUTH_VERIFICATION = 'AUTH_VERIFICATION',
	REGISTER_SUCCESS = 'REGISTER_SUCCESS',
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.REGISTER]: undefined;
	[NAVIGATION_KEYS.AUTH_VERIFICATION]: undefined;
	[NAVIGATION_KEYS.REGISTER_SUCCESS]: undefined;
};
